---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# acsimdata

<!-- badges: start -->
<!-- badges: end -->

The goal of acsimdata is to create simulated data to allow reproducible testing of antigenic cartography methods and quality measures.

## Installation

You can install the released version of acsimdata from Github with:

``` {r install, message=F}
devtools::install_github("drserajames/acsimdata")
```

## Example

This is the basic usage:

```{r example}
library(acsimdata)

# Create random map and distances
rand_map <- map_maker_random(5,5,10, seed=327458)
plot(rand_map$coord, asp=1)

# Add random noise to the distances
noisy_dist <- add_noise(rand_map$dist)

# Convert the distances into titres like HI data
noisy_titres <- dist_to_hi_titre(noisy_dist$noise_dist_table)

# Remove titres to create missing data
miss_noisy_titres <- miss_titres_random(noisy_titres$lessthan_titre, proportion = 0.2)

# Output which can be used with the Racmacs package
miss_noisy_titres$rm_titre
```

