#' Converting antigenic distances to titres
#'
#' Takes an antigenic distance matrix and converts into values like HI titres. Antigenic distances are calculated by taking the logarithm of the HI titres, so the reverse is done here (exponentiated). So that the antigenic distances are generally whole numbers when calculated from standard HI tables, certain defaults are used.
#'
#' @param map an antigenic map generated by a map_maker function
#' @param dists a matrix of antigenic distances
#' @param base the base that should be used for converting distances to titres. The default is base 2
#' @param divisor the numerator for the conversion. This is the number you divide the HI titre by when converting to an antigenic distance.
#'
#' @return
#' @export
#'
#' @examples
#' m <- map_maker_random(5, 5, 10)
#' dist_to_hi_titre(m)
dist_to_hi_titre <- function(map, dists, base=2, divisor=10){

  if(!missing(map)){
    dists <- map$dist
    n_antigens <- map$params$n_antigens
    n_sera <- map$params$n_sera
    which_antigens <- grep("AG", rownames(dists))
    which_sera <- grep("SR", colnames(dists))
  }else{
    which_antigens <- grep("AG", rownames(dists))
    which_sera <- grep("SR", colnames(dists))
    n_antigens <- length(which_antigens)
    n_sera <- length(which_sera)
  }

  raw_titre <- divisor*base^dists
  round_titre <- divisor*base^round(dists)
  hi_titre <- round_titre[which_antigens, which_sera]

  out <- NULL
  out$dist <- dists
  out$raw_titre <- raw_titre
  out$hi_titre <- hi_titre
  return(out)
}

